# Generated by Django 4.2.1 on 2023-05-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='AchievementOfUser',
        ),
    ]
