# Generated by Django 4.2.1 on 2023-05-21 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_role', to='users.role'),
        ),
    ]
