# Generated by Django 4.2.1 on 2023-06-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='snils',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
