# Generated by Django 4.2.1 on 2023-05-16 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LevelChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvailableAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Краткое название')),
                ('points', models.IntegerField(verbose_name='Баллы')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.activitychoice', verbose_name='Тип деятельности')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.levelchoice', verbose_name='Уровень мероприятия')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.rolechoice', verbose_name='Роль студента (участник или организатор)')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Краткое название')),
                ('picture', models.ImageField(null=True, upload_to='images/', verbose_name='Грамота, диплом, справка')),
                ('points', models.IntegerField(default=0, verbose_name='Баллы')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.availableachievement', verbose_name='Достижение или деятельность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
