# Generated by Django 4.2.1 on 2023-05-20 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_alter_achievement_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='points',
        ),
    ]
