# Generated by Django 4.2.1 on 2023-05-21 11:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docs', '0003_alter_achievement_options_remove_achievement_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Достижение пользователя', 'verbose_name_plural': 'Достижения пользователей'},
        ),
        migrations.AlterModelOptions(
            name='availableachievement',
            options={'verbose_name': 'Доступное к выбору достижение', 'verbose_name_plural': 'Все доступные к выбору достижения'},
        ),
        migrations.AddField(
            model_name='achievement',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Подтверждено системой'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='is_moderated',
            field=models.BooleanField(default=False, verbose_name='Проверено модератором'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))], verbose_name='Грамота, диплом, справка'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
