# Generated by Django 4.2.1 on 2023-05-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_alter_achievement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.TextField(max_length=70, verbose_name='Краткое название'),
        ),
    ]
