# Generated by Django 4.2.1 on 2023-05-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_alter_achievement_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='is_rejected',
            field=models.BooleanField(default=False, verbose_name='Отклонено модератором'),
        ),
    ]
